In [2]:
import numpy as np
import matplotlib.pyplot as plt

X_train = np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
y_train = np.array([460,232,178])

print(X_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]


In [3]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [ ]:
def predict_single_loop(x,w,b):
    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i]*w[i]
        p = p_i + p
    # Working with multiple feature but predicting element by element
    p = p + b
    return p
    
x_vec = X_train[0,:]
# print(x_vec)
f_wb = predict_single_loop(x_vec,w_init,b_init)
print(f_wb)


3
459.9999976194083


In [17]:
# This can be implemented using the dot product as well

def predict_value(x,w,b):
    f_wb = np.dot(x,w) + b
    return f_wb

x_vec = X_train[0,:]
print(x_vec)
f_wb = predict_value(x_vec,w_init,b_init)
print(f_wb)
    

[2104    5    1   45]
459.9999976194083
